In [1]:
import numpy as np
from IPython.display import clear_output

In [8]:
final = 10
a = np.zeros((final,final))
x = 5
y = 5
a[7][7] = 5
altx = x
alty = y
a[x][y] = 1
print(a)
direction = 'q'
while direction != 'e':
    direction = input("Enter a direction: ")
    if direction == 'd':
        if y < final-1 and a[x][y+1] != 5:
            y = y + 1
    elif direction == 'a':
        if y > 0 and a[x][y-1] !=5:
            y = y - 1
    elif direction == 'w':
        if x > 0 and a[x-1][y] != 5:
            x = x - 1
    elif direction == 's':
        if x < final-1 and a[x+1][y] != 5:
            x = x + 1
    a[altx][alty] = 0
    a[x][y] = 1
    altx = x
    alty = y
    clear_output(wait=False)
    print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
