In [9]:
import numpy as np
from IPython.display import clear_output
import random

In [21]:
final = 10
starting_value = 5
player = 1
block = 4

In [22]:
a = np.zeros((final,final))
x = starting_value
y = starting_value
altx = x
alty = y
a[x][y] = player
for x in range(100):
    x = random.randint(0,final-1)
    y = random.randint(0,final-1)
    if x != starting_value and y != starting_value:
        a[x][y] = block
print(a)
direction = 'q'
x = altx
y = alty
while direction != 'e':
    direction = input("Enter a direction: ")
    if direction == 'd':
        if y < final-1 and a[x][y+1] != block:
            y = y + 1
    elif direction == 'a':
        if y > 0 and a[x][y-1] != block:
            y = y - 1
    elif direction == 'w':
        if x > 0 and a[x-1][y] != block:
            x = x - 1
    elif direction == 's':
        if x < final-1 and a[x+1][y] != block:
            x = x + 1
    a[altx][alty] = 0
    a[x][y] = 1
    altx = x
    alty = y
    clear_output(wait=False)
    print(a)

[[0. 4. 4. 4. 4. 0. 0. 4. 0. 4.]
 [0. 4. 4. 0. 0. 0. 4. 0. 4. 0.]
 [4. 4. 4. 0. 4. 0. 4. 4. 0. 4.]
 [0. 0. 4. 4. 0. 0. 4. 4. 4. 4.]
 [4. 0. 4. 4. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 1. 0. 4. 0. 4. 4. 4. 0.]
 [0. 4. 0. 4. 4. 0. 4. 4. 0. 4.]
 [0. 4. 4. 0. 0. 0. 4. 4. 0. 4.]
 [4. 0. 4. 4. 4. 0. 0. 4. 0. 4.]]
